= Texts API

=== Send SMS
'''
Example shows how to send SMS to 2 recipients with local time restrictions
[source,java]
    CfApi11Client client = new CfApi11Client("login", "password");
    Date localBeginTime = setSeconds(setMinutes(setHours(new Date(), 10), 10), 10);
    Date localEndTime = setSeconds(setMinutes(setHours(new Date(), 11), 20), 20);
    SendTextRequest request = SendTextRequest.create()
        .name("Send Text Java API Client")
        .defaultBroadcast(true)
        .scrubDuplicates(true)
        .labels(asList("label1", "label2"))
        .recipients(Arrays.asList(
            new ToNumber("12132212384"),
            new ToNumber("16505339974"))
        )
        .config(TextBroadcastConfig.create()
            .fromNumber("67076")
            .message("Api test message")
            .strategy(BigMessageStrategy.SEND_MULTIPLE)
            .timeZoneRestriction(new LocalTimeZoneRestriction(localBeginTime, localEndTime))
        )
        .build();
    long id = client.textsApi().send(request);

=== Query texts
'''
Find texts by provided criteria. The example below shows all searchable fields
[source,java]
    CfApi11Client client = new CfApi11Client("login", "password");
    Date intervalBegin = setYears(setMonths(setDays(
        setSeconds(setMinutes(setHours(new Date(), 0), 0), 0), 27), 0), 2016);
    Date intervalEnd = setYears(setMonths(setDays(
        setSeconds(setMinutes(setHours(new Date(), 20), 20), 20), 20), 11), 2016);
    QueryTextsRequest request = QueryTextsRequest.create()
        .broadcastId(1L)
        .batchId(2L)
        .inbound(true)
        .intervalBegin(intervalBegin)
        .intervalEnd(intervalEnd)
        .fromNumber("67076")
        .toNumber("14243876936")
        .labelName("labelName")
        .states(asList(ActionState.FINISHED))
        .result(asList(TextResult.RECEIVED, TextResult.SENT))
        .maxResults(10)
        .firstResult(1)
        .build();
        List<Text> texts = client.textsApi().query(request);

=== Get text
'''
Example how to get a single Text instance for a given text id.
[source,java]
    CfApi11Client client = new CfApi11Client("login", "password");
    Text text = client.textsApi().get(12345678L);
